### ISSUE TITLE
Create Navigation Bar 3

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#10]
- As user
- i want to have a navigation bar
- So that i can navigate to pages
### Description

![Untitled-2022-05-03-1901 excalidraw(3)](https://user-images.githubusercontent.com/96203909/174809400-880b79f9-99e4-4a27-a27d-f849896d1adc.svg)

### AC
- [ ] Navigation bar
- [ ] Navigate through the pages with a click on an icon

### Tasks
- [ ] Create a new branch
- [ ] Install React Routing
- [ ] Create Route for my Homepage
- [ ] Create Navigation bar
- [ ] Add the Route-Link to the navigation bar
- [ ] Embed the link into an svg icon
- [ ] Testing
- [ ] Storybook

### Complexity
L

### Previous Story
https://github.com/desplodur/capstone-project/issues/3
