### ISSUE TITLE
Create Profile Page 5

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#12]
- As a user
- I want to have a profile page
- So that i can edit my profile

### Description:
![Untitled-2022-05-03-1901 excalidraw(5)](https://user-images.githubusercontent.com/96203909/174994254-b90051be-9fb1-4b9a-a6d9-3900821b9c07.svg)

### AC:
- [x] /profile Page
- [x] Username gets displayed
- [x] Edit Username button

### Tasks:
- [x] Create new branch
- [x] Create new page
- [x] Create route for page
- [x] Create link to the route
- [x] Create testing
- [x] Create story

### Complexity:
M

### Previous Story
#10

**Comment by lkk95** [comment]
Good Job! 
You just have a typo in the tasks: Create **l**ink to the route
