### ISSUE TITLE
Give Answers On Questions 6

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#13]
- As a user
- I want to give answers to questions
- So that i can help my classmates

### AC
- [ ] "Give Answer" Button
- [ ] A click on the button opens the question
- [ ] Open questions have an area where answers can be given
- [ ] Given Answers get displayed below the question

### Tasks
- [ ] Create new branch
- [ ] Add a "Give Answer" Button to the component
- [ ] Add form to the component
- [ ] Add answer-Array to question-Object
- [ ] On Submit pushs an answer into the answer-Array
- [ ] Answers get rendered my mapping over below the question
- [ ] Add useState toggle function
- [ ] "Give Answer" button toggles state
- [ ] Add conditional rendering to the answers and the form

### Difficulty 
L

### Previous stories
#5
