### ISSUE TITLE
Add Zustand

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#19]
As a Developer
I want to add global state management
So that i can use and manage my data on all sites

### AC:
- [x] Existing questions get displayed on the question page
- [x] New questions get displayed on the question page
- [x] New answers get displayed on the question page

### Tasks:
- [x] Install Zustand
- [x] create custom hook 
- [x] move Questions useState into the custom hook

### Previous Stories
#9 #16
