### ISSUE TITLE
Add Basic Styling

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#28]
As a developer
i want to style my app
so that it looks good in the sprint review

## Description 
![Untitled-2022-05-03-1901 excalidraw(6)](https://user-images.githubusercontent.com/96203909/176179279-aa3b6b57-01f1-46d2-91b2-d027ca9164ca.svg)

## AC
- [ ] Basic style for the application

## Tasks
- [ ] Append footer to the bottom of the app
- [ ] Edit styled.js in components
