### ISSUE TITLE
Form Dialog

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#29]
As a user
I want to get a notification when i submit a form
so that i know that my input is saved

## Description 

![Untitled-2022-05-03-1901 excalidraw(7)](https://user-images.githubusercontent.com/96203909/176393360-e37910e3-de06-4c46-8d78-d87de5b26a3d.svg)

## AC 
- [ ] submitting a form opens a dialog
- [ ] Dialog shows submit message

## Tasks
- [ ] Create dialog component
- [ ] The dialog gets a form specific message
- [ ] call open the dialog on the submit button

## Difficulty
S

## Previous stories
#3 #16

**Comment by JessicaLoers** [comment]
Hi @desplodur ✌️
Nice feature, nice User Story. I've just a few minor comments. 
- markdown bug in your description headline 

**AC**: 
- what (text) is displayed?
- what is displayed when the submit has not worked?
