### ISSUE TITLE
Create Question 2

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#3]
- As a user
- I want to have an question create area
- So that i can ask my classmates things i did not understand

# Description 

![Untitled-2022-05-03-1901 excalidraw](https://user-images.githubusercontent.com/96203909/174759390-d07907d1-f106-4786-9fa4-faf3054fa2e8.svg)

# AC
- [x] Instruction for the app user
- [x] Area where the user can ask his question

# Tasks:
- [x] Create new branch
- [x] Create input form component
- [x] Create an Array for the questions 
- [x] on Submit pushes  a new question Object to the Array
- [x] Append component to the homepage
- [x] Testing
- [x] Storybook

# Complexity 
Medium

# Previous Story
https://github.com/desplodur/capstone-project/issues/5

**Comment by mbosselmann** [comment]
Hi Laurenz,
you are welcome! 💪 

I understand your point. Therefore, you should think about if there is a User Story that will be needed first to display the submitted question. Maybe you have a question card user story or question card list user story? Then, you could link to this one and describe that the question will be rendered by using this component. Does this help? :)

And one point: The wireframe should be between your value proposition and your acceptance criteria:
- As a user...
- Description
- Acceptance Criteria
- Tasks
- Complexity

**Comment by desplodur** [comment]
Hey,

i changed the user stories order, so that i create the question component before i create my question. :)

Thanks again for your help
