### ISSUE TITLE
Edit My Answer

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#30]
As a user
i want to edit my answer
so that i can reformulate my answer

## AC
- [ ] Users can just edit their own answers
- [ ] The answer changes after editing

## Tasks
- [ ] add edit button for answers into the answer component
- [ ] create function to update the answer object
- [ ] call function on submit

## Previous story
#49
