### ISSUE TITLE
Show All

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#32]
As a user 
i want to see closed questions
so that i can look at the answers again

## Description
![Untitled-2022-05-03-1901 excalidraw(10)](https://user-images.githubusercontent.com/96203909/176443220-39f6da31-8090-45f9-a5fd-eb58e75c709e.svg)

## AC
- [ ] Show closed questions switch/button
- [ ] Filter questions depending on button status

## Tasks
- [ ] Add a switch to the questions page
- [ ] Add a answered status to the answer object
- [ ] Check if a question is answered before returning the question component
- [ ] change the filter with click on the button

## Difficulty
S

## Previous stories
#33
