### ISSUE TITLE
Close Question

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#33]
As a user 
I want to close a question
so that it does not get displayed anymore

## AC
- [ ] Button to close a question
- [ ] Closed Questions do not get displayed

## Tasks
- [ ] Add answered value to question array
- [ ] Set default value to false
- [ ] Add button into question component
- [ ] toggle answered value onClick
- [ ] Add filter before array.map
