### ISSUE TITLE
Question status indicator

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#34]
As a user
i want to have an question status indicator 
so that i can see if a question is already answered

## AC
- [x] Icon which shows the status of a question

## Tasks
- [x] Add icon to the question component
- [x] conditional style depending on the question status
