### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#36]
As a developer
i want my buttons to be a component

## AC
- [ ] Button gets children
- [ ] Button gets onClick function
- [ ] Button gets spreaded args

## Tasks
- [ ] Create button component folder
- [ ] Create default function for button
- [ ] Create button variants
- [ ] Add simple storybook
- [ ] Add basic testing
