### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#41]
As a developer
i want to refactor my code
so that im ready for the next user stories

## AC 
- [x] Change name function
- [x] Capital letter components
- [x] Flat data structure

## Tasks
- [x] Create new Database file
- [x] Create flat data structure
- [x] Adjust existing functions to the new dataStructure
- [x] Rename components
- [x] Create function to change userName

**Comment by lkk95** [comment]
Good idea! 👍🏼
