### ISSUE TITLE
Bonus feature

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#43]
As a user
i want to know all of my stats in the app
so that i can compete with my fellow students

## AC
- [ ] Overview on how many questions i asked
- [ ] Overview on how many answers i gave

## Tasks
- [ ] Add counter function for all the questions of the active user
- [ ] Add counter function for all the answers of the active user
- [ ] Create component to display all stats
- [ ] Add component to the profile page

## Difficulty 
M
