### ISSUE TITLE
Change username refactor

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#44]
As a user 
i want to change my username 
so that i can give me nice nicknames

## AC
- [ ] Change username form changes my username

## Tasks 
- [ ] Add useStore function to change the username
- [ ] Create update function for the users Database
