### ISSUE TITLE
Login feature

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#45]
As a user 
i want to have my own account
so I can stand out from the crowd

## AC
- [ ] Login with Github
- [ ] Account name gets displayed

## Tasks
- [ ] Understand Pforte library
- [ ] Create Login page 
- [ ] Create users database
- [ ] Login function sets active user
