### ISSUE TITLE
Database storage

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#46]
As a User 
i want to see questions from other people
so that i can answer them

## AC 
- [ ] Every question gets stored in a database
- [ ] CRUD operations

## Tasks
- [ ] Create questions database
- [ ] create useFetch.js file
- [ ] create CRUD operations
- [ ] Connect operations to useStore file

## Difficulty
- [ ] M - L
