### ISSUE TITLE
Write Storybook

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#48]
as a developer
i want to use storybook 
so that i can see every state of my components

## AC
- [ ] Every component has a stories file
- [ ] Every Story displays the component
## Tasks
- [ ] Add Storybook files 
- [ ] Write Storybook parametes
