### ISSUE TITLE
Answer Component

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#49]
As a developer 
i want my answers to be components
so that i my code is cleaner

## AC
- [ ] answer component
- [ ] Every answer is a component

## Tasks 
- [ ] Create answer component
- [ ] Import component into the questionComponent
- [ ] Add styled components

## Complexity
S

## Previous stories
#25
