### ISSUE TITLE
Show Questions 1

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#5]
- As a user
- I want to see all questions on the homepage
- So that i can have an overview of the questions

## Description

![Untitled-2022-05-03-1901 excalidraw(1)](https://user-images.githubusercontent.com/96203909/174760524-a41b8f55-620a-4bc6-b35d-60de410af32d.svg)

## Acceptance Criteria
- [x] Existing questions get displayed on the homepage

## Tasks
- [x] Create a new branch
- [x] Create Question component
- [x] Create Question Array with dummy questions
- [x] Map over all Questions and return the component
- [x] Storybook
- [x] Testing

## Complexity
M

**Comment by desplodur** [comment]
Please take a look at my user story

**Comment by mbosselmann** [comment]
Hi Laurenz,
I like your user story! 💪 Nothing to complain. :) Just an idea: You can work with checkboxes and add Storybook and testing as tasks.
