### ISSUE TITLE
Question Component Refactor

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#54]
As a user 
i want the to see the question on my whole screen
So that its easier to interact with it

## AC
- [ ] Click on QuestionCard opens QuestionDetails

## Tasks
- [ ] Add QuestionDetailPage
- [ ] Add QuestionDetails Component
- [ ] Add id specific route
- [ ] Add useNavigate
- [ ] Add QuestionDetails page style

## Complexity
L
