### ISSUE TITLE
Design Refactoring

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#55]
As a developer
i want my app to look clean
so that the users enjoy using it

## AC
- [ ] Nice and clean user interface
- [ ] Improved UX

## Tasks
- [ ] Build svg component
- [ ] Improve existing styled components structure
- [ ] Add profile picture
- [ ] Add profile component styling
- [ ] Add create page styling
-
## Complexity
M
