### ISSUE TITLE
Add React Query

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#62]
As a developer
i want to use optimistic updates
so that my app responds directly

## AC
- [ ] Direct response on user interactions

## Tasks
- [ ] Remove Zustand
- [ ] Add React Query
- [ ] Add useFetch.js
- [ ] Add useQuery.js
- [ ] Change stored data into queries
