### ISSUE TITLE
Questions On Separate Page 4

### ISSUE THREAD

**Issue by desplodur** [desplodur/capstone-project#9]
- As a user
- I want to have all the existing questions on a second page
- So that i have a better overview of the questions

### Description:
![Untitled-2022-05-03-1901 excalidraw(2)](https://user-images.githubusercontent.com/96203909/174807430-68776d98-e3fb-49d6-8863-49f576d9561d.svg)

### AC:
- [x] Questions page
- [x] All Questions get displayed on the questions page

### Tasks:
- [x] Create new branch
- [x] Create new page
- [x] Change existing template route
- [x] Change existing link to the route
- [x] Import the QuestionComponent into the Question-Page
- [x] Create Dummy Array for questions

### Complexity:
M

### Previous Story
#3 #10

**Comment by lkk95** [comment]
Hey Laurenz, this looks very good :)
One little suggestion: In the AC maybe change the first point to i.e. "routing to questions Page". I think that is more clear. But that is up to you ;)

**Comment by desplodur** [comment]
> Hey Laurenz, this looks very good :) One little suggestion: In the AC maybe change the first point to i.e. "routing to questions Page". I think that is more clear. But that is up to you ;)

Thanks for the feedback. I made some adjustments :)
